### ISSUE TITLE
*.pro file associations aren't there

### ISSUE THREAD

**Issue by MyriaCore** [sebagomez/vsprolog#4]
I use *.pro files with SWI Prolog, but they aren't counted. Is there a way to change it so it knows?

**Comment by sebagomez** [comment]
Sure, let me take a look at it

**Comment by sebagomez** [comment]
Updated vsix at the [marketplace](https://marketplace.visualstudio.com/items?itemName=sebastiangomez.VSProlog)

Enjoy

**Comment by MyriaCore** [comment]
Thanks man!
